import ObjectId from "../util/ObjectId";
import Group from "./Group";
import { Interaction } from "./Interaction";
import { Relationship } from "./Relationship";

/**
 * Contact class
 */
class Contact {

    _id: string;    // Unique ID for contact, generated by mongoDB

    // TODO: remove the | undefined as I implement more fields

    // Metadata
    dateAdded?: Date;               // date contact was added to database
    dateLastUpdated?: Date;         // last time any field was updated
    dateLastInteracted?: Date;      // last time user interacted with contact, either in person or virtually. Generated from log
    source?: string;                // where contact came from (i.e. "imported from vCard", "added manually", "imported from LinkedIn")
    serviceFlags?: string[] | undefined;        // TODO: warning flags ("malformed data", "no name" etc.)

    // Contact information
    alias?: string[] | undefined;    // Array of aliases, if no first + last name, choose first alias
    firstName?: string;
    lastName?: string;
    photoUri?: string[] | undefined;
    title?: string;        // description of user (i.e. "promoter", "landlord", "swe @ google")
    notes?: string;
    birthday?: Date | undefined;

    // Physical addresses
    address?: string[] | undefined;     // TODO: change to address object (string + description + time there) // current addresses (can have multiple)
    formerAddresses?: string[] | undefined;    // TODO: change to address object (string + description + time there) // former addresses

    // Phone numbers
    primaryPhone?: string | undefined;      // TODO: change to phone object
    alternatePhone?: string[] | undefined;  // TODO: change to phone object + description tuple

    // Email addresses
    personalEmail?: string | undefined;
    workEmail?: string | undefined;

    // Social media
    facebook?: string | undefined;
    twitter?: string | undefined;
    instagram?: string | undefined;
    linkedin?: string | undefined;
    snapchat?: string | undefined;
    github?: string | undefined;

    // Education
    highSchool?: string | undefined;        // TODO: change to school object (school name + dates attended)
    college?: string | undefined;           // TODO: change to school object (school name + dates attended)
    gradSchool?: string | undefined;        // TODO: change to school object (school name + dates attended)

    // Work
    currentJob?: string | undefined;        // TODO: change to job object
    pastJobs?: string[] | undefined;        // TODO: change to job object

    // Relationships
    relationships?: Relationship[] | undefined;

    // Groups
    groups?: Group[] | undefined;

    // Interactions
    interactions?: Interaction[] | undefined;


    [key: string]: any; // Index signature for dynamic properties
    constructor(miscFields: { [key: string]: any });
    constructor();

    constructor(miscFields?: { [key: string]: any }) {
        this._id = ObjectId();  
        if (miscFields) {
            for (const key in miscFields) {
                if (miscFields.hasOwnProperty(key)) {
                    this[key] = miscFields[key];
                }
            }
        } 
    }


    // TODO: normalize more fields
    normalize(): void {
        if (this.primaryPhone) {
            // TODO: use a number parser library
            this.primaryPhone = this.primaryPhone
        }
    }

    addRelationship(relationship: Relationship) {
        this.relationships = this.relationships || [];
        this.relationships.push(relationship);
    }


}


export default Contact;