import Interaction from "./Interaction";
import Relationship from "./Relationship";

/**
 * Contact class
 */
class Contact {

    _id?: string | undefined;    // Unique ID for contact, generated by mongoDB

    // Metadata
    dateAdded?: Date | undefined;        // date contact was added to database
    dateLastUpdated?: Date | undefined;          // last time any field was updated
    dateLastInteracted?: Date | undefined;   // last time user interacted with contact, either in person or virtually. Generated from log
    source?: string | undefined;        // where contact came from (i.e. "imported from vCard", "added manually", "imported from LinkedIn")

    // Contact information
    alias?: string[] | undefined;    // Array of aliases, if no first + last name, choose first alias
    firstName?: string | undefined;
    lastName?: string | undefined;
    photoUri?: string[] | undefined;
    title?: string | undefined;        // description of user (i.e. "promoter", "landlord", "swe @ google")
    notes?: string | undefined;
    birthday?: Date | undefined;

    // Physical address
    address?: string[] | undefined;     // TODO: change to address object (string + description tuple)
    formerAddresses?: string[] | undefined;    // TODO: change to address object (string + description tuple)

    // Phone numbers
    primaryPhone?: string | undefined;      // TODO: change to phone object
    alternatePhone?: string[] | undefined;  // TODO: change to phone object + description tuple

    // Email addresses
    personalEmail?: string | undefined;
    workEmail?: string | undefined;

    // Social media
    facebook?: string | undefined;
    twitter?: string | undefined;
    instagram?: string | undefined;
    linkedin?: string | undefined;
    snapchat?: string | undefined;
    github?: string | undefined;

    // Education
    highSchool?: string | undefined;        // TODO: change to school object (school name + dates attended)
    college?: string | undefined;           // TODO: change to school object (school name + dates attended)
    gradSchool?: string | undefined;        // TODO: change to school object (school name + dates attended)

    // Work
    currentJob?: string | undefined;        // TODO: change to job object
    pastJobs?: string[] | undefined;        // TODO: change to job object

    // Relationships
    relationships?: Relationship[] | undefined;   

    // Groups
    groups?: string[] | undefined;

    // Interactions
    interactions?: Interaction[] | undefined;

    [key: string]: any; // Index signature for dynamic properties

    constructor(miscFields: { [key: string]: any }) {       
        for (const key in miscFields) {
            if (miscFields.hasOwnProperty(key)) {
                this[key] = miscFields[key];
            }
        }
    }

    // TODO: normalize more fields
    normalize(): void {
        if (this.primaryPhone) {
            // TODO: use a number parser library
            this.primaryPhone = this.primaryPhone
        }
    }

    addRelationship(relationship: Relationship) {
        this.relationships = this.relationships || [];
        this.relationships.push(relationship);
    }
}


export default Contact;