
/**
 * Contact class with required fields and additional optional fields
 * 
 * required fields:
 *  - _id
 *  - alias
 *  - dateAdded
 *  - dateLastUpdated
 */
class Contact {

    _id?: string | undefined;    // Unique ID for contact, generated by mongoDB

    // Metadata - TODO: change dateLastInteracted below to interaction object
    dateAdded?: Date | undefined;        // date contact was added to database
    dateLastUpdated?: Date | undefined;          // last time any field was updated
    dateLastInteracted?: Date | undefined;   // last time user interacted with contact, either in person or virtually. Generated from log

    // Contact information
    alias: string[];    // Array of aliases, if no first + last name, choose first alias
    firstName?: string | undefined;
    lastName?: string | undefined;
    photoUri?: string[] | undefined;
    title?: string | undefined;        // description of user (i.e. "promoter", "landlord", "swe @ google")
    notes?: string | undefined;
    birthday?: Date | undefined;

    // Physical address
    address?: string[] | undefined;     // TODO: change to address object (string + description tuple)
    formerAddresses?: string[] | undefined;    // TODO: change to address object (string + description tuple)

    // Phone numbers
    primaryPhone?: string | undefined;      // TODO: change to phone object
    alternatePhone?: string[] | undefined;  // TODO: change to phone object + description tuple

    // Email addresses
    personalEmail?: string | undefined;
    workEmail?: string | undefined;

    // Social media
    facebook?: string | undefined;
    twitter?: string | undefined;
    instagram?: string | undefined;
    linkedin?: string | undefined;
    snapchat?: string | undefined;
    github?: string | undefined;

    // Education
    highSchool?: string | undefined;        // TODO: change to school object (school name + dates attended)
    college?: string | undefined;           // TODO: change to school object (school name + dates attended)
    gradSchool?: string | undefined;        // TODO: change to school object (school name + dates attended)

    // Work
    currentJob?: string | undefined;        // TODO: change to job object
    pastJobs?: string[] | undefined;        // TODO: change to job object

    // Relationships
    relationships?: string[] | undefined;

    // Groups
    groups?: string[] | undefined;

    // Interactions
    interactions?: string[] | undefined;

    [key: string]: any; // Index signature for dynamic properties

    constructor(miscFields: { [key: string]: any }) {
        this._id = miscFields._id;
        this.alias = miscFields.alias;
        this.dateAdded = miscFields.dateAdded;
        this.dateLastUpdated = miscFields.dateLastUpdated;

        for (const key in miscFields) {
            if (miscFields.hasOwnProperty(key)) {
                this[key] = miscFields[key];
            }
        }
    }
}


export default Contact;